# -*- coding: utf-8 -*-
"""ASSIGNMENT1_NAVYASREE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I5vhNrq0cRPx4wcfaFKkQ-knUyeyF-OQ

**Arvind just started learning python and he is very interested to know how he can print his name on the screen using python. Write a program to print Arvind on the screen. Print your name and age as well using a python print statement.**
"""

print("Arvind")
print("navyasree")
print(21)

"""**Himanshi is confused with different shapes. Write a program in python to print different shapes using these symbols: “|”, “-”, “/”, “\”.**"""

print("Square:")
print(" ----- ")
print("|     |")
print("|     |")
print(" ----- ")
print()

print("Triangle:")
print("   /\\   ")
print("  /  \\  ")
print(" /    \\ ")
print(" ------ ")
print()

print("Pentagon:")
print("   -----   ")
print("  /     \\  ")
print(" /       \\ ")
print("|         |")
print("|         |")
print(" --------- ")
print()

print("Hexagon:")
print("  -------  ")
print(" /       \\ ")
print("/         \\")
print("\\         /")
print(" \\       / ")
print("  -------  ")
print()

print("Diamond:")
print("   /\\   ")
print("  /  \\  ")
print("  \\  /  ")
print("   \\/   ")
print()

print("House:")
print("   /\\   ")
print("  /  \\  ")
print(" /    \\ ")
print("-------")
print("|     |")
print("|     |")
print("|-----|")
print()

print("Rectangle:")
print(" -------- ")
print("|        |")
print("|        |")
print("|        |")
print("|        |")
print(" -------- ")
print()

print("Parallelogram:")
print("    ------")
print("   /     /")
print("  /     / ")
print(" /     /  ")
print(" ------   ")
print()

"""**Sahil challenged Chirag to print the names of his friend in different lines using a single print statement. Sahil thought that this would be impossible to do. To help Chirag write a python program to print the names of your five friends in five different lines using a single print statement**

"""

print("manjula\nmythri\nsiri\nhema\nmanu")

"""**1:A teacher told students to write an essay on themselves. Nidhi created a python program that can generate an essay just by taking inputs. She shared the program with her friends to help them. Write a python program that can take inputs like name, age, address, etc, and convert it into an essay. ● Rakshita wants to create a simple chatbot using python language. Write a program in python to help Rakshita in creating the chatbot. ● Hint: with the help of variables store the answers of the user and use it for further conversation by the chatbot. ● Example : ● >> ● Hi, I am a chatbot. What is your name? ● >>Nidhi ● Oh, Nidhi in which grade you are right now? ● >>8 ● Nidhi you are in 8th grade. Can I ask you one question? yes or no? ● >>yes ● Tell me 1024+98=? ● >>1122 ● Good! Your answer is correct. Bye ● >>bye**

"""

#essay creation

name = input("What is your name? ")
age = input("How old are you? ")
grade = input("Which grade are you in? ")
hobby = input("What is your favorite hobby? ")
favorite_subject = input("What is your favorite subject? ")
dream = input("What is your dream or goal in life? ")

essay = """My name is {}. I am {} years old and currently studying in grade {}.I live in a beautiful place where I enjoy spending time with my family and friends.One of my favorite activities is {}. It helps me relax and makes me happy.In school, I particularly enjoy {} because it is interesting and I love learning new things.In the future, I aspire to become {}. I believe that with hard work and dedication, I can achieve my dreams.""".format(name, age, grade, hobby, favorite_subject, dream)

print("Generated Essay:")
print(essay)

# chatbot creation
print("Hi, I am a chatbot. What is your name?")
name = input(">> ")

print("Oh, {}, in which grade are you right now?".format(name))
grade = input(">> ")

print("{}, you are in {}th grade. Can I ask you one question? yes or no?".format(name,grade))
permission = input(">> ")

if permission == "yes":
    print("Tell me, what is 1024 + 98?")
    answer = input(">> ")

    if answer == "1122":
        print("Good! Your answer is correct.")
    else:
        print("Oops! That's not correct, but don't worry, you'll get it next time!")
else:
    print("No problem! Maybe next time.")

print("Bye!")

"""**Himanshu sells notebooks. Sometimes it becomes a bit difficult for him to calculate the total amount to charge from the customer. To help Himanshu create a program that asks the user to enter the number of books to buy and then print the amount to be paid. ● Hint: Assume the cost of one notebook - $2**"""

one_notebook_price = 2

number_of_notebooks = int(input("Please enter the number of notebooks you want to buy: "))
total_amount = number_of_notebooks * one_notebook_price

print("The total amount to be paid for {} notebook(s) is: ${}".format(number_of_notebooks,total_amount))

"""**Shubh is excited to do something mathematical in python. He decided to create a program that could add, subtract, multiply and divide two numbers. To help Shubh write a python program to apply addition, subtraction, multiplication, and division between two numbers. ● Rakshita wants to calculate her age. So she subtracted her year of birth from the current year. Her classmates also wanted to find their age in the same way. So she decides to write a python program where students can input their year of birth, then the program will print their age. Write the same program to find your age and help your classmates in finding their age**"""

num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

addition = num1 + num2
print("The addition of {} and {} is: {}".format(num1,num2,addition))

subtraction = num1 - num2
print("The subtraction of {} from {} is: {}".format(num1,num2,subtraction))

multiplication = num1 * num2
print("The multiplication of {} and {} is: {}".format(num1,num2,multiplication))

if num2 != 0:
    division = num1 / num2
    print("The division of {} by {} is: {}".format(num1,num2,division))
else:
    print("Division by zero is not possible")

current_year = 2024
year_of_birth = int(input("Enter your year of birth: "))
age = current_year - year_of_birth

print("You are {} years old.".format(age))