# -*- coding: utf-8 -*-
"""Programs using While loop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11qR4Tsho6mEKKOV1sS7w8FJwJWj3MvvY
"""

#Multiplication table using while loop
num = int(input("enter the number that you want the multiplication table:: "))
i = 1
while i<=10:
  print(num,"X",i,"=",num*i)
  i+=1

# Input: Number to check
num = int(input("Enter a number: "))

i = 2

is_prime = True

if num <= 1:
    is_prime = False

while i * i <= num:
    if num % i == 0:
        is_prime = False
        break
    i += 1

if is_prime:
    print(f"{num} is a prime number.")
else:
    print(f"{num} is not a prime number.")

#Quiz using while loop

score = 0
question_number = 1
total_questions = 3

# Start the quiz
while question_number <= total_questions:
    if question_number == 1:
        print("Question 1: What is 2 + 2?")
        answer = input("Your answer: ")
        if answer == "4":
            print("Correct!")
            score += 1
        else:
            print("Wrong! The correct answer is 4.")

    elif question_number == 2:
        print("Question 2: What is the capital of India?")
        answer = input("Your answer: ")
        if answer == "New Delhi":
            print("Correct!")
            score += 1
        else:
            print("Wrong! The correct answer is New Delhi.")

    elif question_number == 3:
        print("Question 3: what is the national bird of India?")
        answer = input("Your answer: ")
        if answer == "Peacock":
            print("Correct!")
            score += 1
        else:
            print("Wrong! The correct answer is Peacock.")
    question_number += 1
print("Quiz finished! Your final score is {}/{}.".format(score, total_questions))

