# -*- coding: utf-8 -*-
"""Python Basic Exam

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nTLIKUH3ClhZDUekCjivezAFFCBy5g5o

**It's Victoria's birthday and Alex, being her brother, wants to give something to victoria. Alex wants to give a beautiful tree designed using print() in python as a gift because Victoria loves trees.**

**write a program to print a beautiful tree using print() and \ | / ( ) symbols where ever required to help alex so that he can gift a tree design to victoria with greetings saying "Happy Birthday Victoria" at the bottom**
"""

print("        (      )       ")
print("       (        )      ")
print("      (          )     ")
print("     (            )    ")
print("    (              )   ")
print("     ***        ***    ")
print("        |      |       ")
print("        |      |       ")
print("        |      |       ")
print("        |      |       ")
print("       /        \      ")
print("      /          \     ")
print("************************")
print("Happy Birthday Victoria")
print("************************")

"""**Eliana, a 10th grade class teacher, is facing difficulty in calculating the average percentage using the percentages obtained by all the students in class. The percentages are as follows,**

Student 1 : 85

Student 2 : 96

Student 3 : 92.67

Student 4 : 71.89

Student 5 : 67

Student 6 : 73.5

Student 7 : 55

Student 8 : 58.12

Student 9 : 99.23

Student 10 : 73

**Write a program to add all the above percentages together and divide it by number of students to get the average percentage.**
"""

s1 = 85   #student1 percentage
s2 = 96
s3 = 92.67
s4 = 71.89
s5 = 67
s6 = 73.5
s7 = 55
s8 = 58.12
s9 = 99.23
s10 = 73
total_sum_of_percentages = s1+s2+s3+s4+s5+s6+s7+s8+s9+s10
total_no_of_students=10
avg_percentage=total_sum_of_percentages/total_no_of_students
print("Average percentage = ",avg_percentage)

"""**Jack learnt in maths class about Armstrong Numbers. Armstrong
numbers are numbers where if each individual digit of the number was to
be raised to a power of 3, the sum of that would be equal to the number
itself. For Example, 370 = 3*3 + 77 +0*0 = 370 The teacher gave
Jack the number 153. Can we check if the number is a armstrong
number or not.**
"""

As_num = 153
d1 = As_num // 100
d2 =(As_num //10)%10
d3 =As_num%10
sum_of_powers =d1**3 +d2**3 +d3**3

if sum_of_powers == As_num:
  print("{} is a Armstrong Number".format(As_num))
else:
  print("{} is a not Armstrong Number".format(As_num))

print(153//100)
print((153//10)%10)
print(153%10)

"""Jill went to Maths class today and learnt all about even and odd
numbers. Jill found out that if a number is divisible by 2 that is the
remainder is 0 when divided by 2 the number is even. If not, then the
number is odd. For Jill’s home assignment, the teacher gave the task to
find out using python if the number 24 is divisible by 2 or not. The
remainder should be displayed using a print statement.
"""

Given_number = 24
if Given_number % 2 ==0:
  print("The remainder is ::",Given_number % 2)
  print("The {} is even".format(Given_number))
else:
  print("The remainder is ::",Given_number % 2)
  print("The {} is odd".format(Given_number))

